In [1]:
import sys
sys.path.append("../src")

In [2]:
import time
import httpx
import pandas as pd

In [3]:
from smogcast.ingest.gios import get_all_stations

In [4]:
stations = get_all_stations()

In [5]:
len(stations)

288

In [6]:
stations_with_pm_poland = []

for i, station in enumerate(stations, start=1):
    print(f"{i}/{len(stations)} - {station['Nazwa stacji']}")

    station_id = station["Identyfikator stacji"]

    url = (
        "https://api.gios.gov.pl/pjp-api/"
        f"v1/rest/station/sensors/{station_id}"
    )

    response = httpx.get(url, timeout=30.0)
    response.raise_for_status()

    sensor_data = response.json()

    sensors = sensor_data[
        "Lista stanowisk pomiarowych dla podanej stacji"
    ]

    pm_sensors = [
        sensor
        for sensor in sensors
        if sensor.get("Wskaźnik") in {
            "pył zawieszony PM10",
            "pył zawieszony PM2.5",
        }
    ]

    if pm_sensors:
        stations_with_pm_poland.append(
            {
                "station_id": station_id,
                "station_name": station["Nazwa stacji"],
                "city": station["Nazwa miasta"],
                "voivodeship": station["Województwo"],
                "pm_sensors": pm_sensors,
            }
        )

    time.sleep(0.2)

1/288 - Czerniawa
2/288 - Dzierżoniów, ul. Piłsudskiego
3/288 - Kłodzko, ul. Szkolna
4/288 - Legnica, Al. Rzeczypospolitej
5/288 - Oława, ul. Żołnierzy Armii Krajowej
6/288 - Oleśnica, ul. Brzozowa
7/288 - Osieczów
8/288 - Polkowice, ul. Kasztanowa
9/288 - Szczawno-Zdrój, ul. Kolejowa
10/288 - Wałbrzych, ul. Wysockiego
11/288 - Wrocław, ul. Bartnicza
12/288 - Wrocław, ul. Na Grobli
13/288 - Wrocław, wyb. Conrada-Korzeniowskiego
14/288 - Wrocław, ul. Orzechowa
15/288 - Wrocław, Al. Wiśniowa
16/288 - Zgorzelec, ul. Bohaterów Getta
17/288 - Grudziądz, ul. Piłsudskiego
18/288 - Inowrocław, ul. Solankowa
19/288 - Toruń, ul. Wały gen. Sikorskiego
20/288 - Bydgoszcz, ul. Fieldorfa
21/288 - Bydgoszcz, Pl. Poznański
22/288 - Bydgoszcz, ul. Warszawska
23/288 - Ciechocinek, ul. Tężniowa
24/288 - Grudziądz, ul. Sienkiewicza
25/288 - Koniczynka, Pojezierze Chełmińskie
26/288 - Toruń, ul. Dziewulskiego
27/288 - Toruń, ul. Przy Kaszowniku
28/288 - Włocławek, ul. Okrzei
29/288 - Zielonka, Bory Tucholskie
30/288 - Biała Podlaska, ul. Orzechowa
31/288 - Jarczew, IMGW
32/288 - Kraśnik, ul. Koszarowa
33/288 - Lublin, ul. Śliwińskiego
34/288 - Lublin, ul. Obywatelska
35/288 - Radzyń Podlaski, ul. Sitkowskiego
36/288 - Wilczopole
37/288 - Zamość, ul. Hrubieszowska
38/288 - Brzeziny, ul. Reformacka
39/288 - Gajew, Ujęcie Wody
40/288 - Łódź, ul. Czernika
41/288 - Łódź, ul. Gdańska
42/288 - Łódź, ul. Legionów
43/288 - Pabianice, ul. Konstantynowska
44/288 - Parzniewice, Ujęcie Wody
45/288 - Piotrków Trybunalski, ul. Krakowskie Przedmieście
46/288 - Radomsko, ul. Rolna
47/288 - Tomaszów Mazowiecki ul. Św. Antoniego
48/288 - Wieluń, ul. POW
49/288 - Zduńska Wola, ul. Królewska
50/288 - Zgierz, ul. Mielczarskiego
51/288 - Gorzów Wlkp. ul. Kosynierów Gdyńskich
52/288 - Gorzów Wlkp. ul. Piłsudskiego
53/288 - Smolary Bytnickie
54/288 - Sulęcin ul. Dudka
55/288 - Wschowa ul. Kazimierza Wielkiego
56/288 - Żary, ul. Szymanowskiego
57/288 - Zielona Góra ul. Krótka
58/288 - Bochnia, ul. Konfederatów Barskich
59/288 - Gorlice, ul. Krasińskiego
60/288 - Kraków, Aleja Krasińskiego
61/288 - Kraków, ul. Bujaka
62/288 - Kraków, ul. Bulwarowa
63/288 - Nowy Sącz, ul. Nadbrzeżna
64/288 - Skawina, Os. Ogrody
65/288 - Szymbark
66/288 - Tarnów, ul. Bitwy pod Studziankami
67/288 - Trzebinia, Os. Związku Walki Młodych
68/288 - Tuchów, ul. Chopina
69/288 - Niepołomice, ul. 3 Maja
70/288 - Zakopane, ul. Sienkiewicza
71/288 - Belsk Duży, IGF PAN
72/288 - Granica, KPN
73/288 - Legionowo, ul. Zegrzyńska
74/288 - Otwock, ul. Brzozowa
75/288 - Piastów, ul. Pułaskiego
76/288 - Płock, ul. Królowej Jadwigi
77/288 - Płock, ul. Reja
78/288 - Radom, ul. 25 Czerwca
79/288 - Radom, ul. Hallera
80/288 - Radom, ul. Tochtermana
81/288 - Siedlce, ul. Konarskiego
82/288 - Warszawa, Al. Niepodległości
83/288 - Warszawa, ul. Krzywoń
84/288 - Warszawa, ul. Tołstoja
85/288 - Warszawa, ul. Wokalna
86/288 - Warszawa, ul. Kondratowicza
87/288 - Żyrardów, ul. Roosevelta
88/288 - Kędzierzyn-Koźle, ul. Śmiałego
89/288 - Kluczbork, ul. Mickiewicza
90/288 - Olesno, ul. Słowackiego
91/288 - Opole, Os. Armii Krajowej
92/288 - Zdzieszowice, ul. Piastów
93/288 - Białystok, ul. Warszawska
94/288 - Borsukowizna, Szkółka Leśna
95/288 - Łomża, ul. Sikorskiego
96/288 - Jarosław, ul. Pruchnicka
97/288 - Jaslo, ul. Sikorskiego
98/288 - Krosno, ul. Kletówki
99/288 - Nisko, ul. Szklarniowa
100/288 - Przemyśl, ul. Grunwaldzka
101/288 - Rzeszów, Al. Rejtana
102/288 - Sanok, ul. Sadowa
103/288 - Tarnobrzeg, ul. Dąbrowskiej
104/288 - Gdańsk, ul. Powstańców Wielkopolskich
105/288 - Słupsk, ul. Kniaziewicza
106/288 - Gdańsk, ul. Powstańców Warszawskich
107/288 - Gdańsk, ul. Wyzwolenia
108/288 - Gdynia, ul. Porębskiego
109/288 - Gdańsk, ul. Leczkowa
110/288 - Kościerzyna, ul. Targowa
111/288 - Malbork, ul. Mickiewicza
112/288 - Lębork, ul. Malczewskiego
113/288 - Liniewko Kościerskie
114/288 - Kwidzyn, ul. Sportowa
115/288 - Łeba, IMGW
116/288 - Busko-Zdrój, ul. Rokosza
117/288 - Nowiny, ul. Parkowa
118/288 - Ożarów, Os. Wzgórze
119/288 - Połaniec, ul. Ruszczańska
120/288 - Starachowice, ul. Złota
121/288 - Bielsko-Biała, ul. Kossak-Szczuckiej
122/288 - Bielsko-Biała, ul. Sternicza
123/288 - Częstochowa, Al. AK/Jana Pawła II
124/288 - Częstochowa, ul. Baczyńskiego
125/288 - Częstochowa, ul. Zana
126/288 - Dąbrowa Górnicza, ul. Tysiąclecia
127/288 - Gliwice, ul. Mewy
128/288 - Godów, ul. Gliniki
129/288 - Katowice, ul. Kossutha
130/288 - Knurów, ul. Jedności Narodowej
131/288 - Myszków, ul. Miedziana
132/288 - Rybnik, ul. Borki
133/288 - Sosnowiec, ul. Lubelska
134/288 - Tarnowskie Góry, ul. Litewska
135/288 - Tychy, ul. Tołstoja
136/288 - Ustroń, ul. Sanatoryjna
137/288 - Wodzisław Śląski, ul. Gałczyńskiego
138/288 - Złoty Potok, Leśniczówka
139/288 - Żywiec, ul. Kopernika
140/288 - Elbląg, ul. Bażyńskiego
141/288 - Gołdap, ul. Jaćwieska
142/288 - Nidzica, ul.Traugutta
143/288 - Olsztyn, ul. Puszkina
144/288 - Diabla Góra, Puszcza Borecka
145/288 - Gniezno, ul. Paczkowskiego
146/288 - Konin, ul. Wyszyńskiego
147/288 - Nowy Tomyśl, ul. Sienkiewicza
148/288 - Pila, ul. Kusocińskiego
149/288 - Poznań, ul. Spychalskiego
150/288 - Poznań, ul. Szymanowskiego
151/288 - Wągrowiec, ul. Lipowa
152/288 - Poznań, ul. Dąbrowskiego
153/288 - Piaski, Krzyżówka
154/288 - Borówiec, ul. Drapałka
155/288 - Kalisz, ul. Wyszyńskiego
156/288 - Widuchowa
157/288 - Koszalin, Al. Armii Krajowej
158/288 - Koszalin, ul. Spasowskiego
159/288 - Myślibórz, ul. Za Bramką
160/288 - Szczecinek, ul. 1 Maja
161/288 - Szczecinek, ul. Przemysłowa
162/288 - Szczecin, ul. Andrzejewskiego
163/288 - Szczecin, ul. Piłsudskiego
164/288 - Szczecin, ul. Łączna
165/288 - Jelenia Góra, ul. Sokoliki
166/288 - Iława, ul.Andersa
167/288 - Czerwionka-Leszczyny, ul. Kopalniana
168/288 - Ostrołęka, ul. Hallera
169/288 - Jelenia Góra, ul. Ogińskiego
170/288 - Dębica, ul.Grottgera
171/288 - Krempna, Ośrodek edukacyjno-muzealny MPN
172/288 - Głogów, ul. Wita Stwosza
173/288 - Szarów, ul. Spokojna
174/288 - Brodnica, ul. Kochanowskiego
175/288 - Pleszew, Al. Mickiewicza
176/288 - Skierniewice, ul. Konopnickiej
177/288 - Włocławek, ul. Kaliska
178/288 - Nakło nad Notecią, ul. Św. Wawrzyńca
179/288 - Guty Duże
180/288 - Kielce, ul. Warszawska 210
181/288 - Ełk, ul. Piłsudskiego
182/288 - Głubczyce, ul. Ratuszowa
183/288 - Ostróda, ul. Piłsudskiego
184/288 - Łódź, Al. Jana Pawła II
185/288 - Uniejów, ul. Zamkowa
186/288 - Bełchatów, ul. Edwardów
187/288 - Duszniki-Zdrój, ul. Sportowa
188/288 - Mielec, ul. Pogodna
189/288 - Kaszów
190/288 - Tarnów, ul. Ks. Romana Sitko
191/288 - Iwonicz Zdrój, ul. Rąba
192/288 - Kraków, ul. Złoty Róg
193/288 - Sucha Beskidzka, ul. Nieszczyńskiej
194/288 - Rzeszów, Al. Piłsudskiego
195/288 - Stalowa Wola, ul. Wojska Polskiego
196/288 - Kraków, Os. Piastów
197/288 - Sieradz, ul. Polna
198/288 - Świdnica, ul. Folwarczna
199/288 - Poznan, ul. Hetmańska
200/288 - Bielsko-Biała, ul. Partyzantów
201/288 - Opole, ul. Koszyka
202/288 - Rymanów Zdrój, ul. Parkowa
203/288 - Mielec, ul. Biernackiego
204/288 - Rabka-Zdrój, ul. Orkana
205/288 - Kraków, Os. Wadów
206/288 - Opoczno, ul. Skłodowskiej-Curie
207/288 - Żory, Os. Gen. Władysława Sikorskiego
208/288 - Włocławek, ul. Gniazdowskiego
209/288 - Małogoszcz, ul. Słoneczna
210/288 - Oświęcim, ul. J. Bema
211/288 - Złockie, szkoła podstawowa
212/288 - Koziegłowy, Os. Leśne
213/288 - Wieniec Zdrój, ul. Wieniecka
214/288 - Florianka, RPN
215/288 - Kołobrzeg, ul. Żółkiewskiego
216/288 - Warszawa, ul. Chrościckiego
217/288 - Warszawa, ul. Bajkowa
218/288 - Suwałki, ul. Pułaskiego 26
219/288 - Białystok, ul. 42 Pułku Piechoty
220/288 - Kielce, ul. Targowa
221/288 - Legnica, ul. Polarna
222/288 - Nowa Ruda, ul. Jeziorna
223/288 - Lubliniec, ul. ks. Szymały
224/288 - Zielona Góra,ul.Wyszyńskiego
225/288 - Olkusz, ul. Cegielniana
226/288 - Kraków, Os. Swoszowice
227/288 - Koszalin, ul. Chopina
228/288 - Biała, ul. Kmicica
229/288 - Chełm, ul. Połaniecka
230/288 - Nałęczów, Al. Małachowskiego
231/288 - Zabierzów, ul. Wapienna
232/288 - Zawiercie, ul. K.I.Gałczyńskiego
233/288 - Goczałkowice-Zdrój, ul. Parkowa
234/288 - Łask, ul. Narutowicza
235/288 - Bydgoszcz, ul. Jeździecka
236/288 - Gołuchów, Ujęcie Wody
237/288 - Racibórz, ul. Wojska Polskiego
238/288 - Białystok, Al. Piłsudskiego
239/288 - Jastrzębie-Zdrój, Al. J.Piłsudskiego/Harcerska
240/288 - Augustów, Uzdrowisko
241/288 - Trzebnica, ul. 3 Maja
242/288 - Lublin, ul. Okopowa
243/288 - Krasnobród, ul. Sanatoryjna
244/288 - Opatów, ul. Partyzantów
245/288 - Połczyn-Zdrój, ul. Solankowa
246/288 - Gdańsk, Al. Grunwaldzka
247/288 - Kielce, ul. Warszawska 108
248/288 - Sopot, ul. Bitwy Pod Płowcami
249/288 - Konstancin-Jeziorna, ul. Żeromskiego
250/288 - Wejherowo, ul. Dworcowa
251/288 - Cieszyn, ul. Chopina
252/288 - Brzeg, ul. Poprzeczna
253/288 - Poznań ul. Szwajcarska
254/288 - Mosina, ul. Czereśniowa
255/288 - Kielce, ul. Jurajska
256/288 - Warszawa, IMGW
257/288 - Nowa Sól
258/288 - Myślenice
259/288 - Nowy Targ, Al. Tysiąclecia
260/288 - Kraków, ul. Kamieńskiego
261/288 - Krapkowice, ul. 3 Maja
262/288 - Pszczyna, ul. Batorego
263/288 - Wysowa-Zdrój, Park Zdrojowy
264/288 - Rzeszów, ul. Starzyńskiego
265/288 - Katowice, ul. Dudy-Gracza
266/288 - Białystok, ul. Upalna
267/288 - Kępno ul. Sportowa
268/288 - Leszno, ul. Bolesława Prusa
269/288 - Zabrze, ul. M. Skłodowskiej-Curie
270/288 - Wysokie Mazowieckie, ul. 1 Maja
271/288 - Rzeszów, ul. Kwiatkowskiego
272/288 - Krasne
273/288 - Ciechanów, ul. Kraszewskiego
274/288 - Tomaszów Lubelski, ul. Janusza Petera
275/288 - Krotoszyn, ul. Olimpijska
276/288 - Gdańsk, ul. Lawendowe Wzgórze
277/288 - Kraków, ul. Półłanki
278/288 - Nysa, ul. Rodziewiczówny 1
279/288 - Lubań, ul. Ludowa
280/288 - Warszawa, ul. Grochowska
281/288 - Warszawa, Al. Solidarności
282/288 - Szlichtyngowa, ul. Przemysłowa
283/288 - Ostrowiec Świętokrzyski, ul. Polna
284/288 - Solec-Zdrój, ul. Leśna
285/288 - ul. Sportowa 15
286/288 - Solec Kujawski, ul. Tartaczna 10
287/288 - Tczew, ul. Czyżykowska
288/288 - Braniewo, ul. PCK

In [7]:
stations_pm_poland_df = pd.DataFrame(
    [
        {
            "station_id": station["station_id"],
            "station_name": station["station_name"],
            "city": station["city"],
            "voivodeship": station["voivodeship"],
            "pm10_count": sum(
                sensor.get("Wskaźnik") == "pył zawieszony PM10"
                for sensor in station["pm_sensors"]
            ),
            "pm25_count": sum(
                sensor.get("Wskaźnik") == "pył zawieszony PM2.5"
                for sensor in station["pm_sensors"]
            ),
        }
        for station in stations_with_pm_poland
    ]
)

In [8]:
stations_pm_poland_df

,station_id,station_name,city,voivodeship,pm10_count,pm25_count
0,11,Czerniawa,Czerniawa,DOLNOŚLĄSKIE,1,0
1,16,"Dzierżoniów, ul. Piłsudskiego",Dzierżoniów,DOLNOŚLĄSKIE,1,0
2,38,"Kłodzko, ul. Szkolna",Kłodzko,DOLNOŚLĄSKIE,1,1
3,52,"Legnica, Al. Rzeczypospolitej",Legnica,DOLNOŚLĄSKIE,2,1
4,70,"Oława, ul. Żołnierzy Armii Krajowej",Oława,DOLNOŚLĄSKIE,2,1
...,...,...,...,...,...,...
260,20568,"Solec-Zdrój, ul. Leśna",Solec Zdrój,ŚWIĘTOKRZYSKIE,2,1
261,20590,ul. Sportowa 15,Kobierzyce,DOLNOŚLĄSKIE,1,0
262,20591,"Solec Kujawski, ul. Tartaczna 10",Solec Kujawski,KUJAWSKO-POMORSKIE,1,1
263,20607,"Tczew, ul. Czyżykowska",Tczew,POMORSKIE,1,1
264,20647,"Braniewo, ul. PCK",Braniewo,WARMIŃSKO-MAZURSKIE,2,1

In [9]:
len(stations_pm_poland_df)

265

In [10]:
stations_both_df = stations_pm_poland_df[
    (stations_pm_poland_df["pm10_count"] > 0)
    & (stations_pm_poland_df["pm25_count"] > 0)
].copy()

In [11]:
stations_both_df

,station_id,station_name,city,voivodeship,pm10_count,pm25_count
2,38,"Kłodzko, ul. Szkolna",Kłodzko,DOLNOŚLĄSKIE,1,1
3,52,"Legnica, Al. Rzeczypospolitej",Legnica,DOLNOŚLĄSKIE,2,1
4,70,"Oława, ul. Żołnierzy Armii Krajowej",Oława,DOLNOŚLĄSKIE,2,1
8,109,"Wałbrzych, ul. Wysockiego",Wałbrzych,DOLNOŚLĄSKIE,2,2
10,117,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,1,1
...,...,...,...,...,...,...
259,20567,"Ostrowiec Świętokrzyski, ul. Polna",Ostrowiec Świętokrzyski,ŚWIĘTOKRZYSKIE,2,1
260,20568,"Solec-Zdrój, ul. Leśna",Solec Zdrój,ŚWIĘTOKRZYSKIE,2,1
262,20591,"Solec Kujawski, ul. Tartaczna 10",Solec Kujawski,KUJAWSKO-POMORSKIE,1,1
263,20607,"Tczew, ul. Czyżykowska",Tczew,POMORSKIE,1,1
264,20647,"Braniewo, ul. PCK",Braniewo,WARMIŃSKO-MAZURSKIE,2,1

In [12]:
len(stations_both_df)

144

In [13]:
stations_both_df["voivodeship"].value_counts()

voivodeship
MAZOWIECKIE            20
PODKARPACKIE           13
ŚLĄSKIE                13
DOLNOŚLĄSKIE           11
MAŁOPOLSKIE            10
KUJAWSKO-POMORSKIE      9
PODLASKIE               9
POMORSKIE               9
LUBUSKIE                8
ŚWIĘTOKRZYSKIE          8
LUBELSKIE               7
WIELKOPOLSKIE           7
ZACHODNIOPOMORSKIE      6
ŁÓDZKIE                 5
OPOLSKIE                5
WARMIŃSKO-MAZURSKIE     4
Name: count, dtype: int64

In [14]:
capital_cities = {
    "DOLNOŚLĄSKIE": "Wrocław",
    "KUJAWSKO-POMORSKIE": "Bydgoszcz",
    "LUBELSKIE": "Lublin",
    "LUBUSKIE": "Gorzów Wielkopolski",
    "ŁÓDZKIE": "Łódź",
    "MAŁOPOLSKIE": "Kraków",
    "MAZOWIECKIE": "Warszawa",
    "OPOLSKIE": "Opole",
    "PODKARPACKIE": "Rzeszów",
    "PODLASKIE": "Białystok",
    "POMORSKIE": "Gdańsk",
    "ŚLĄSKIE": "Katowice",
    "ŚWIĘTOKRZYSKIE": "Kielce",
    "WARMIŃSKO-MAZURSKIE": "Elbląg",
    "WIELKOPOLSKIE": "Poznań",
    "ZACHODNIOPOMORSKIE": "Szczecin",
}

In [15]:
capital_stations = []

for voivodeship, city in capital_cities.items():
    matches = stations_both_df[
        (stations_both_df["voivodeship"] == voivodeship)
        & (stations_both_df["city"] == city)
    ]

    if not matches.empty:
        capital_stations.append(matches.iloc[0])
    else:
        print(f"Brak pasującej stacji: {voivodeship} - {city}")

In [16]:
capital_stations_df = pd.DataFrame(
    capital_stations
).reset_index(drop=True)

In [17]:
capital_stations_df[
    [
        "voivodeship",
        "city",
        "station_name",
        "pm10_count",
        "pm25_count",
    ]
]

,voivodeship,city,station_name,pm10_count,pm25_count
0,DOLNOŚLĄSKIE,Wrocław,"Wrocław, wyb. Conrada-Korzeniowskiego",1,1
1,KUJAWSKO-POMORSKIE,Bydgoszcz,"Bydgoszcz, Pl. Poznański",1,1
2,LUBELSKIE,Lublin,"Lublin, ul. Śliwińskiego",1,1
3,LUBUSKIE,Gorzów Wielkopolski,Gorzów Wlkp. ul. Kosynierów Gdyńskich,2,1
4,ŁÓDZKIE,Łódź,"Łódź, ul. Czernika",1,2
5,MAŁOPOLSKIE,Kraków,"Kraków, Aleja Krasińskiego",1,1
6,MAZOWIECKIE,Warszawa,"Warszawa, Al. Niepodległości",1,1
7,OPOLSKIE,Opole,"Opole, Os. Armii Krajowej",1,1
8,PODKARPACKIE,Rzeszów,"Rzeszów, Al. Rejtana",2,1
9,PODLASKIE,Białystok,"Białystok, ul. Warszawska",1,2
10,POMORSKIE,Gdańsk,"Gdańsk, ul. Powstańców Warszawskich",1,1
11,ŚLĄSKIE,Katowice,"Katowice, ul. Kossutha",2,2
12,ŚWIĘTOKRZYSKIE,Kielce,"Kielce, ul. Targowa",2,1
13,WARMIŃSKO-MAZURSKIE,Elbląg,"Elbląg, ul. Bażyńskiego",2,2
14,WIELKOPOLSKIE,Poznań,"Poznań, ul. Dąbrowskiego",1,1
15,ZACHODNIOPOMORSKIE,Szczecin,"Szczecin, ul. Andrzejewskiego",2,2

In [18]:
len(capital_stations_df)

16

In [19]:
(
    (capital_stations_df["pm10_count"] > 0)
    & (capital_stations_df["pm25_count"] > 0)
).all()

np.True_

In [20]:
capital_station_ids = capital_stations_df[
    "station_id"
].tolist()

In [21]:
capital_station_ids

[117,
 156,
 258,
 361,
 295,
 400,
 530,
 590,
 671,
 609,
 729,
 814,
 11195,
 861,
 944,
 986]

In [22]:
len(capital_station_ids)

16

In [23]:
sensor_records = []

for station in stations_with_pm_poland:
    if station["station_id"] not in capital_station_ids:
        continue

    for sensor in station["pm_sensors"]:
        indicator = sensor.get("Wskaźnik")

        if indicator == "pył zawieszony PM10":
            parameter = "PM10"

        elif indicator == "pył zawieszony PM2.5":
            parameter = "PM2.5"

        else:
            continue

        sensor_records.append(
            {
                "station_id": station["station_id"],
                "station_name": station["station_name"],
                "city": station["city"],
                "voivodeship": station["voivodeship"],
                "sensor_id": sensor["Identyfikator stanowiska"],
                "parameter": parameter,
            }
        )

In [24]:
sensor_records_df = pd.DataFrame(sensor_records)

In [25]:
sensor_records_df = (
    sensor_records_df
    .drop_duplicates(subset="sensor_id")
    .reset_index(drop=True)
)

In [26]:
sensor_records_df

,station_id,station_name,city,voivodeship,sensor_id,parameter
0,117,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,669,PM10
1,117,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,670,PM2.5
2,156,"Bydgoszcz, Pl. Poznański",Bydgoszcz,KUJAWSKO-POMORSKIE,965,PM10
3,156,"Bydgoszcz, Pl. Poznański",Bydgoszcz,KUJAWSKO-POMORSKIE,966,PM2.5
4,258,"Lublin, ul. Śliwińskiego",Lublin,LUBELSKIE,1832,PM10
5,258,"Lublin, ul. Śliwińskiego",Lublin,LUBELSKIE,1833,PM2.5
6,295,"Łódź, ul. Czernika",Łódź,ŁÓDZKIE,2069,PM10
7,295,"Łódź, ul. Czernika",Łódź,ŁÓDZKIE,2071,PM2.5
8,295,"Łódź, ul. Czernika",Łódź,ŁÓDZKIE,2072,PM2.5
9,361,Gorzów Wlkp. ul. Kosynierów Gdyńskich,Gorzów Wielkopolski,LUBUSKIE,2421,PM10
10,361,Gorzów Wlkp. ul. Kosynierów Gdyńskich,Gorzów Wielkopolski,LUBUSKIE,2422,PM10
11,361,Gorzów Wlkp. ul. Kosynierów Gdyńskich,Gorzów Wielkopolski,LUBUSKIE,26165,PM2.5
12,400,"Kraków, Aleja Krasińskiego",Kraków,MAŁOPOLSKIE,2750,PM10
13,400,"Kraków, Aleja Krasińskiego",Kraków,MAŁOPOLSKIE,2752,PM2.5
14,530,"Warszawa, Al. Niepodległości",Warszawa,MAZOWIECKIE,3584,PM10
15,530,"Warszawa, Al. Niepodległości",Warszawa,MAZOWIECKIE,3585,PM2.5
16,590,"Opole, Os. Armii Krajowej",Opole,OPOLSKIE,3938,PM10
17,590,"Opole, Os. Armii Krajowej",Opole,OPOLSKIE,3939,PM2.5
18,609,"Białystok, ul. Warszawska",Białystok,PODLASKIE,4024,PM10
19,609,"Białystok, ul. Warszawska",Białystok,PODLASKIE,4025,PM2.5
20,609,"Białystok, ul. Warszawska",Białystok,PODLASKIE,32441,PM2.5
21,671,"Rzeszów, Al. Rejtana",Rzeszów,PODKARPACKIE,4387,PM10
22,671,"Rzeszów, Al. Rejtana",Rzeszów,PODKARPACKIE,4389,PM2.5
23,671,"Rzeszów, Al. Rejtana",Rzeszów,PODKARPACKIE,14466,PM10
24,729,"Gdańsk, ul. Powstańców Warszawskich",Gdańsk,POMORSKIE,4681,PM10
25,729,"Gdańsk, ul. Powstańców Warszawskich",Gdańsk,POMORSKIE,28227,PM2.5
26,814,"Katowice, ul. Kossutha",Katowice,ŚLĄSKIE,5376,PM10
27,814,"Katowice, ul. Kossutha",Katowice,ŚLĄSKIE,5377,PM10
28,814,"Katowice, ul. Kossutha",Katowice,ŚLĄSKIE,5378,PM2.5
29,814,"Katowice, ul. Kossutha",Katowice,ŚLĄSKIE,5379,PM2.5
30,861,"Elbląg, ul. Bażyńskiego",Elbląg,WARMIŃSKO-MAZURSKIE,5683,PM10
31,861,"Elbląg, ul. Bażyńskiego",Elbląg,WARMIŃSKO-MAZURSKIE,5684,PM10
32,861,"Elbląg, ul. Bażyńskiego",Elbląg,WARMIŃSKO-MAZURSKIE,5685,PM2.5
33,861,"Elbląg, ul. Bażyńskiego",Elbląg,WARMIŃSKO-MAZURSKIE,20691,PM2.5
34,944,"Poznań, ul. Dąbrowskiego",Poznań,WIELKOPOLSKIE,6085,PM10
35,944,"Poznań, ul. Dąbrowskiego",Poznań,WIELKOPOLSKIE,20176,PM2.5
36,986,"Szczecin, ul. Andrzejewskiego",Szczecin,ZACHODNIOPOMORSKIE,6352,PM10
37,986,"Szczecin, ul. Andrzejewskiego",Szczecin,ZACHODNIOPOMORSKIE,6353,PM10
38,986,"Szczecin, ul. Andrzejewskiego",Szczecin,ZACHODNIOPOMORSKIE,6354,PM2.5
39,986,"Szczecin, ul. Andrzejewskiego",Szczecin,ZACHODNIOPOMORSKIE,6355,PM2.5
40,11195,"Kielce, ul. Targowa",Kielce,ŚWIĘTOKRZYSKIE,19749,PM10
41,11195,"Kielce, ul. Targowa",Kielce,ŚWIĘTOKRZYSKIE,19752,PM10
42,11195,"Kielce, ul. Targowa",Kielce,ŚWIĘTOKRZYSKIE,19753,PM2.5

In [27]:
sensor_records_df["sensor_id"].duplicated().sum()

np.int64(0)

In [28]:
sensor_records_df.to_parquet(
    "../data/raw/gios_capital_sensors_poland.parquet",
    index=False,
)

In [29]:
sensor_records = sensor_records_df.to_dict("records")

In [30]:
len(sensor_records)

43

In [31]:
date_from = "2025-08-20 00:00"
date_to = "2026-08-20 23:00"

In [32]:
from smogcast.ingest.gios import get_data_for_sensor_records

In [33]:
all_measurements, failed_ranges = get_data_for_sensor_records(
    sensor_records,
    date_from,
    date_to,
    days_per_range=30,
)

1/43 | DOLNOŚLĄSKIE | Wrocław | PM10 | sensor 669
Pobieram sensor 669: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 669: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 669: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 669: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 669: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 669: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 669: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 669: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 669: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 669: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 669: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 669: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 669: 2026-08-15 00:00 - 2026-08-20 23:00

2/43 | DOLNOŚLĄSKIE | Wrocław | PM2.5 | sensor 670
Pobieram sensor 670: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 670: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 670: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 670: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 670: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 670: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 670: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 670: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 670: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 670: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 670: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 670: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 670: 2026-08-15 00:00 - 2026-08-20 23:00

3/43 | KUJAWSKO-POMORSKIE | Bydgoszcz | PM10 | sensor 965
Pobieram sensor 965: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 965: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 965: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 965: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 965: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 965: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 965: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 965: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 965: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 965: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 965: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 965: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 965: 2026-08-15 00:00 - 2026-08-20 23:00

4/43 | KUJAWSKO-POMORSKIE | Bydgoszcz | PM2.5 | sensor 966
Pobieram sensor 966: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 966: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 966: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 966: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 966: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 966: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 966: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 966: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 966: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 966: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 966: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 966: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 966: 2026-08-15 00:00 - 2026-08-20 23:00

5/43 | LUBELSKIE | Lublin | PM10 | sensor 1832
Pobieram sensor 1832: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 1832: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 1832: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 1832: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 1832: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 1832: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 1832: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 1832: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 1832: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 1832: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 1832: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 1832: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 1832: 2026-08-15 00:00 - 2026-08-20 23:00

6/43 | LUBELSKIE | Lublin | PM2.5 | sensor 1833
Pobieram sensor 1833: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 1833: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 1833: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 1833: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 1833: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 1833: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 1833: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 1833: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 1833: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 1833: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 1833: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 1833: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 1833: 2026-08-15 00:00 - 2026-08-20 23:00

7/43 | ŁÓDZKIE | Łódź | PM10 | sensor 2069
Pobieram sensor 2069: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2069: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2069: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2069: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2069: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2069: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2069: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2069: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2069: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2069: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2069: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2069: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2069: 2026-08-15 00:00 - 2026-08-20 23:00

8/43 | ŁÓDZKIE | Łódź | PM2.5 | sensor 2071
Pobieram sensor 2071: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2071: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2071: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2071: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2071: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2071: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2071: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2071: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2071: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2071: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2071: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2071: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2071: 2026-08-15 00:00 - 2026-08-20 23:00

9/43 | ŁÓDZKIE | Łódź | PM2.5 | sensor 2072
Pobieram sensor 2072: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2072: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2072: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2072: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2072: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2072: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2072: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2072: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2072: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2072: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2072: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2072: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2072: 2026-08-15 00:00 - 2026-08-20 23:00

10/43 | LUBUSKIE | Gorzów Wielkopolski | PM10 | sensor 2421
Pobieram sensor 2421: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2421: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2421: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2421: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2421: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2421: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2421: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2421: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2421: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2421: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2421: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2421: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2421: 2026-08-15 00:00 - 2026-08-20 23:00

11/43 | LUBUSKIE | Gorzów Wielkopolski | PM10 | sensor 2422
Pobieram sensor 2422: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2422: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2422: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2422: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2422: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2422: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2422: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2422: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2422: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2422: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2422: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2422: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2422: 2026-08-15 00:00 - 2026-08-20 23:00

12/43 | LUBUSKIE | Gorzów Wielkopolski | PM2.5 | sensor 26165
Pobieram sensor 26165: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 26165: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 26165: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 26165: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 26165: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 26165: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 26165: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 26165: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 26165: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 26165: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 26165: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 26165: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 26165: 2026-08-15 00:00 - 2026-08-20 23:00

13/43 | MAŁOPOLSKIE | Kraków | PM10 | sensor 2750
Pobieram sensor 2750: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2750: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2750: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2750: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2750: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2750: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2750: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2750: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2750: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2750: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2750: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2750: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2750: 2026-08-15 00:00 - 2026-08-20 23:00

14/43 | MAŁOPOLSKIE | Kraków | PM2.5 | sensor 2752
Pobieram sensor 2752: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 2752: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 2752: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 2752: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 2752: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 2752: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 2752: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 2752: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 2752: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 2752: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 2752: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 2752: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 2752: 2026-08-15 00:00 - 2026-08-20 23:00

15/43 | MAZOWIECKIE | Warszawa | PM10 | sensor 3584
Pobieram sensor 3584: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 3584: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 3584: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 3584: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 3584: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 3584: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 3584: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 3584: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 3584: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 3584: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 3584: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 3584: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 3584: 2026-08-15 00:00 - 2026-08-20 23:00

16/43 | MAZOWIECKIE | Warszawa | PM2.5 | sensor 3585
Pobieram sensor 3585: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 3585: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 3585: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 3585: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 3585: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 3585: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 3585: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 3585: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 3585: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 3585: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 3585: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 3585: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 3585: 2026-08-15 00:00 - 2026-08-20 23:00

17/43 | OPOLSKIE | Opole | PM10 | sensor 3938
Pobieram sensor 3938: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 3938: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 3938: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 3938: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 3938: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 3938: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 3938: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 3938: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 3938: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 3938: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 3938: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 3938: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 3938: 2026-08-15 00:00 - 2026-08-20 23:00

18/43 | OPOLSKIE | Opole | PM2.5 | sensor 3939
Pobieram sensor 3939: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 3939: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 3939: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 3939: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 3939: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 3939: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 3939: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 3939: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 3939: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 3939: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 3939: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 3939: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 3939: 2026-08-15 00:00 - 2026-08-20 23:00

19/43 | PODLASKIE | Białystok | PM10 | sensor 4024
Pobieram sensor 4024: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 4024: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 4024: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 4024: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 4024: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 4024: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 4024: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 4024: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 4024: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 4024: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 4024: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 4024: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 4024: 2026-08-15 00:00 - 2026-08-20 23:00

20/43 | PODLASKIE | Białystok | PM2.5 | sensor 4025
Pobieram sensor 4025: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 4025: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 4025: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 4025: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 4025: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 4025: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 4025: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 4025: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 4025: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 4025: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 4025: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 4025: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 4025: 2026-08-15 00:00 - 2026-08-20 23:00

21/43 | PODLASKIE | Białystok | PM2.5 | sensor 32441
Pobieram sensor 32441: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 32441: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 32441: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 32441: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 32441: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 32441: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 32441: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 32441: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 32441: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 32441: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 32441: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 32441: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 32441: 2026-08-15 00:00 - 2026-08-20 23:00

22/43 | PODKARPACKIE | Rzeszów | PM10 | sensor 4387
Pobieram sensor 4387: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 4387: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 4387: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 4387: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 4387: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 4387: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 4387: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 4387: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 4387: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 4387: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 4387: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 4387: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 4387: 2026-08-15 00:00 - 2026-08-20 23:00

23/43 | PODKARPACKIE | Rzeszów | PM2.5 | sensor 4389
Pobieram sensor 4389: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 4389: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 4389: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 4389: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 4389: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 4389: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 4389: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 4389: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 4389: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 4389: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 4389: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 4389: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 4389: 2026-08-15 00:00 - 2026-08-20 23:00

24/43 | PODKARPACKIE | Rzeszów | PM10 | sensor 14466
Pobieram sensor 14466: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 14466: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 14466: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 14466: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 14466: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 14466: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 14466: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 14466: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 14466: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 14466: 2026-05-17 00:00 - 2026-06-16 00:00
Pobieram sensor 14466: 2026-06-16 00:00 - 2026-07-16 00:00
Pobieram sensor 14466: 2026-07-16 00:00 - 2026-08-15 00:00
Pobieram sensor 14466: 2026-08-15 00:00 - 2026-08-20 23:00

25/43 | POMORSKIE | Gdańsk | PM10 | sensor 4681
Pobieram sensor 4681: 2025-08-20 00:00 - 2025-09-19 00:00
Pobieram sensor 4681: 2025-09-19 00:00 - 2025-10-19 00:00
Pobieram sensor 4681: 2025-10-19 00:00 - 2025-11-18 00:00
Pobieram sensor 4681: 2025-11-18 00:00 - 2025-12-18 00:00
Pobieram sensor 4681: 2025-12-18 00:00 - 2026-01-17 00:00
Pobieram sensor 4681: 2026-01-17 00:00 - 2026-02-16 00:00
Pobieram sensor 4681: 2026-02-16 00:00 - 2026-03-18 00:00
Pobieram sensor 4681: 2026-03-18 00:00 - 2026-04-17 00:00
Pobieram sensor 4681: 2026-04-17 00:00 - 2026-05-17 00:00
Pobieram sensor 4681: 2026-05-17 00:00 - 2026-06-16 00:00

In [34]:
len(all_measurements)

225518

In [35]:
len(failed_ranges)

0

In [37]:
df = pd.DataFrame(all_measurements)

In [38]:
df.head()

,Nazwa stacji,Kod stanowiska,Data,Wartość,station_id,sensor_id,station_name,city,voivodeship,Parametr
0,"Wrocław, wyb. Conrada-Korzeniowskiego",DsWrocWybCon-PM10-24g,2025-08-20 00:00:00,29.9,117,669,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,PM10
1,"Wrocław, wyb. Conrada-Korzeniowskiego",DsWrocWybCon-PM10-24g,2025-08-21 00:00:00,23.0,117,669,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,PM10
2,"Wrocław, wyb. Conrada-Korzeniowskiego",DsWrocWybCon-PM10-24g,2025-08-22 00:00:00,21.2,117,669,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,PM10
3,"Wrocław, wyb. Conrada-Korzeniowskiego",DsWrocWybCon-PM10-24g,2025-08-23 00:00:00,23.5,117,669,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,PM10
4,"Wrocław, wyb. Conrada-Korzeniowskiego",DsWrocWybCon-PM10-24g,2025-08-24 00:00:00,10.2,117,669,"Wrocław, wyb. Conrada-Korzeniowskiego",Wrocław,DOLNOŚLĄSKIE,PM10

In [39]:
df["Data"] = pd.to_datetime(df["Data"])

In [40]:
df = df[
    [
        "station_id",
        "sensor_id",
        "station_name",
        "city",
        "voivodeship",
        "Parametr",
        "Data",
        "Wartość",
        "Kod stanowiska",
    ]
]

In [41]:
print("Liczba pomiarów:", len(df))
print("Liczba stacji:", df["station_id"].nunique())
print("Liczba sensorów:", df["sensor_id"].nunique())
print("Najstarszy pomiar:", df["Data"].min())
print("Najnowszy pomiar:", df["Data"].max())

Liczba pomiarów: 225518
Liczba stacji: 16
Liczba sensorów: 43
Najstarszy pomiar: 2025-08-20 00:00:00
Najnowszy pomiar: 2026-08-20 23:00:00

In [42]:
df["Parametr"].value_counts()

Parametr
PM10     114250
PM2.5    111268
Name: count, dtype: int64

In [43]:
df.duplicated(
    subset=["sensor_id", "Data"]
).sum()

np.int64(504)

In [45]:
df = (
    df
    .drop_duplicates(
        subset=["sensor_id", "Data"],
        keep="first",
    )
    .reset_index(drop=True)
)

In [46]:
df.duplicated(
    subset=["sensor_id", "Data"]
).sum()

np.int64(0)

In [47]:
len(df)

225014

In [48]:
df.to_parquet(
    "../data/raw/gios_pm_measurements_1y.parquet",
    index=False,
)

In [49]:
failed_ranges_df = pd.DataFrame(
    failed_ranges,
    columns=["sensor_id", "date_from", "date_to"],
)

failed_ranges_df.to_csv(
    "../data/raw/gios_failed_ranges_1y.csv",
    index=False,
)